apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-spider-api
  labels:
    app: news-spider-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-spider-api
  template:
    metadata:
      labels:
        app: news-spider-api
    spec:
      containers:
        - args:
            - npm
            - start
          name: news-spider-api
          image: docker.io/xinli940207/news_spider_api:1.0.0
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /news_spider_api/config.json
              name: management-api-config
              readOnly: true
              subPath: config.json
      volumes:
        - name: management-api-config
          secret:
            secretName: management-api-config.v1

---
apiVersion: v1
kind: Service
metadata:
  name: news-spider-api
spec:
  ports:
    - port: 5000
  selector:
    app: news-spider-api
