apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-spider-frontend
  labels:
    app: news-spider-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-spider-frontend
  template:
    metadata:
      labels:
        app: news-spider-frontend
    spec:
      containers:
        - args:
            - yarn
            - start
          env:
            - name: REACT_APP_NEWS_SPIDER_API_HOST
              value: 'aede666ff6d774035a6b5c200fb0f088-1578147687.eu-west-3.elb.amazonaws.com'
            - name: REACT_APP_NEWS_SPIDER_API_PORT
              value: '5000'
          name: news-spider-frontend
          image: xinli940207/news_spider_frontend:1.1.2
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: news-spider-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: news-spider-frontend
