apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-spider
  labels:
    app: news-spider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-spider
  template:
    metadata:
      labels:
        app: news-spider
    spec:
      containers:
        - args:
            - node
            - index.js
          env:
            - name: REDIS_HOST
              value: 'redis-service.default.svc.cluster.local'
            - name: REDIS_PORT
              value: '6379'
            - name: MONGO_HOST
              value: 'databaseAdmin:ziggr09kd1ZSdI1dk@mongo-cluster-rs0.default.svc.cluster.local'
            - name: MONGO_PORT
              value: '27017'
            - name: DATABASE
              value: 'admin'
          name: news-spider
          image: docker.io/xinli940207/news_spider:1.1.3
